### ISSUE TITLE
Unable to pip install on Python 3.9.5

### ISSUE THREAD

**Issue by dlink** [546133753/python-sqlparser#1]
Hello,

I am unable to pip install python-sqlparser on Python 3.9.5.   I was using your module for some time on Python 2.7 and it was very helpful. 

Here is the error messages I get.   Thanks

(.venv) $ python --version
Python 3.9.5
(.venv) $ pip install python-sqlparser
Collecting python-sqlparser
  Using cached python-sqlparser-1.2.tar.gz (41 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/dlink/central/.venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-smpyhzd4/python-sqlparser_4bfadfc35e97429abed317b870318e1c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-smpyhzd4/python-sqlparser_4bfadfc35e97429abed317b870318e1c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3n75enzf
         cwd: /tmp/pip-install-smpyhzd4/python-sqlparser_4bfadfc35e97429abed317b870318e1c/
    Complete output (58 lines):
    Traceback (most recent call last):
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 1346, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/http/client.py", line 1253, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/http/client.py", line 1299, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/http/client.py", line 1248, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/http/client.py", line 1008, in _send_output
        self.send(msg)
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/http/client.py", line 948, in send
        self.connect()
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/http/client.py", line 1422, in connect
        self.sock = self._context.wrap_socket(self.sock,
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/ssl.py", line 500, in wrap_socket
        return self.sslsocket_class._create(
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/ssl.py", line 1040, in _create
        self.do_handshake()
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/ssl.py", line 1309, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-smpyhzd4/python-sqlparser_4bfadfc35e97429abed317b870318e1c/setup.py", line 60, in <module>
        download_library()
      File "/tmp/pip-install-smpyhzd4/python-sqlparser_4bfadfc35e97429abed317b870318e1c/setup.py", line 38, in download_library
        urlretrieve(url, file_name)
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 239, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 214, in urlopen
        return opener.open(url, data, timeout)
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 523, in open
        response = meth(req, response)
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 632, in http_response
        response = self.parent.error(
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 555, in error
        result = self._call_chain(*args)
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 494, in _call_chain
        result = func(*args)
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 747, in http_error_302
        return self.parent.open(new, timeout=req.timeout)
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 517, in open
        response = self._open(req, data)
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 534, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 494, in _call_chain
        result = func(*args)
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 1389, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "/home/dlink/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 1349, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)>
    Could not find the general sql parser library in ./general_sql_parser/
    Downloading library from 'http://www.sqlparser.com/dl/gsqlparser_c_linux64_trial_1_1_0.tar.gz'...
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7c/ae/88d8b1b40e06575002960f45effdedf920fd8d96de55d866ffe87abcec04/python-sqlparser-1.2.tar.gz#sha256=c0b21d1df44a02741a8b811a08e06163131fbbfca6b2fcb841724c71184a35e4 (from https://pypi.org/simple/python-sqlparser/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement python-sqlparser (from versions: 1.2)
ERROR: No matching distribution found for python-sqlparser

**Comment by bastienboutonnet** [comment]
I just encountered a similar error on a docker running `python:3.8-slim-buster`

I have the same error as above and tried installing from source (clone the git repo and `pip install .` as well as via PyPI `pip install python-sqlparser`

If there is any way in which I could help, any pointers I'd be more than happy to contribute.

**Comment by bastienboutonnet** [comment]
I found this thread which points to the SSL issue and maybe a solution with a context manager for requests, not sure if this would be something we could patch in here: https://askubuntu.com/questions/1231844/ssl-sslerror-ssl-dh-key-too-small-dh-key-too-small-ssl-c1108
